/**
 * Building the website edition's handoff.
 *
 * The render surface consumes generated 11ty inputs and knows nothing about
 * who produced them. Every field below was read off Studio's
 * `pipeline/content/content.py` and a real published archive page rather than
 * inferred, because the site's templates index into them: `links` drives the
 * per-issue link list, `domains` the fingerprint, `word_count` the stats, and
 * the `audio_*` fields the podcast enclosure.
 */

import type { IssueDoc, Item } from '../shared/types.ts';
import { renderWebsite } from '../shared/render/website.ts';
import { planEdition, bodyLines } from '../shared/render/plan.ts';
import { CDN_HOST } from './integrations/images.ts';
import type { RepoFile } from './integrations/github.ts';

/**
 * Studio stamps its own generator here and its parser accepts three historical
 * variants. Ours names WT Builder, so a tool re-reading these files must be
 * taught this string too.
 */
export const GENERATED_NOTICE =
  '<!-- Generated by WT Builder from the canonical issue; do not edit directly. -->';

export interface AudioFields {
  audio_url?: string;
  audio_duration_seconds?: number;
  audio_byte_size?: number;
  audio_voice?: string;
}

export interface IssueLink {
  text: string;
  url: string;
  domain: string;
  /** The Markdown link as it renders, which the site shows as context. */
  heading_context: string;
  section: string;
}

export interface IssueEntry extends AudioFields {
  id: string;
  number: number;
  subject: string;
  publish_date: string;
  slug: string;
  description: string;
  image: string;
  absolute_url: string;
  domains: string[];
  links: IssueLink[];
  notable_links: IssueLink[];
  briefly_links: IssueLink[];
  word_count: number;
}

/**
 * "WT349 — Owning the Rails", the form every published issue uses. A title
 * that is only the issue's own name carries no editorial content, so it
 * collapses to the bare "WT349" rather than printing "WT349 — 349".
 */
export function subjectFor(doc: IssueDoc): string {
  const n = doc.issue.number;
  const title = doc.issue.title
    .replace(/^The Weekly Thing\b/i, '')
    .replace(/^\s*(?:#|WT)?\s*/i, '')
    .trim();
  if (!title || title === String(n)) return `WT${n}`;
  return `WT${n} — ${title}`;
}

/** Noon UTC, matching every issue already in the archive. */
export function publishTimestamp(date: string): string {
  return `${date}T12:00:00Z`;
}

/** The generated cover art, at its conventional CDN path. */
export function coverImage(issueNumber: number): string {
  return `https://${CDN_HOST}/weekly-thing/${issueNumber}/cover.jpg`;
}

/** Jamie's own properties, which are never outbound links. */
function isOwnDomain(host: string): boolean {
  const bare = host.replace(/^www\./, '');
  return bare === 'thingelstad.com' || bare.endsWith('.thingelstad.com');
}

function hostOf(url: string): string | null {
  try {
    return new URL(url).hostname;
  } catch {
    return null;
  }
}

function linkFor(item: Item, section: string): IssueLink | null {
  const url = item.source_url;
  if (!url) return null;
  const domain = hostOf(url);
  if (!domain) return null;
  const text = item.title ?? url;
  return { text, url, domain, heading_context: `[${text}](${url})`, section };
}

export interface ExtractedLinks {
  links: IssueLink[];
  notable_links: IssueLink[];
  briefly_links: IssueLink[];
  domains: string[];
  word_count: number;
}

/**
 * Links, their sections, the domain fingerprint, and the issue's word count —
 * all derived from the website edition, so they describe what actually shipped.
 */
export function extractLinks(doc: IssueDoc): ExtractedLinks {
  const links: IssueLink[] = [];
  const notable: IssueLink[] = [];
  const briefly: IssueLink[] = [];
  const domains = new Set<string>();
  let words = 0;

  for (const planned of planEdition(doc, 'website')) {
    const section = planned.node.label;
    for (const { item } of planned.items) {
      for (const text of [item.body, item.commentary, item.title]) {
        const flat = bodyLines(text).join(' ');
        if (flat) words += flat.split(/\s+/).filter(Boolean).length;
      }

      if (item.type === 'pinboard_link') {
        const link = linkFor(item, section);
        if (link) {
          links.push(link);
          if (section.toLowerCase() === 'notable') notable.push(link);
          if (section.toLowerCase() === 'briefly') briefly.push(link);
        }
      }

      // Every *outbound* host counts toward the fingerprint, including links
      // written inline in prose. Jamie's own blog is not outbound — a Journal
      // post linking to thingelstad.com is the issue citing itself, and no
      // published issue lists it.
      const urls = [item.source_url ?? ''];
      for (const m of String(item.body ?? '').matchAll(/\]\((https?:\/\/[^)\s]+)/g)) {
        urls.push(m[1]!);
      }
      for (const url of urls) {
        const host = url ? hostOf(url) : null;
        if (host && !isOwnDomain(host)) domains.add(host);
      }
    }
  }

  return {
    links,
    notable_links: notable,
    briefly_links: briefly,
    domains: [...domains].sort(),
    word_count: words,
  };
}

export interface SiteInputsOptions {
  /** Buttondown's id and archive URL, which exist only once the email is drafted. */
  buttondownId?: string;
  absoluteUrl?: string;
  audio?: AudioFields;
  /** Every prior issue's entry, so the index is rewritten whole. */
  priorEntries?: IssueEntry[];
}

export function issueEntry(doc: IssueDoc, opts: SiteInputsOptions = {}): IssueEntry {
  const number = doc.issue.number;
  const extracted = extractLinks(doc);
  return {
    id: opts.buttondownId ?? '',
    number,
    subject: subjectFor(doc),
    publish_date: publishTimestamp(doc.issue.publication_date),
    slug: String(number),
    description: doc.issue.dek ?? '',
    image: coverImage(number),
    absolute_url:
      opts.absoluteUrl ?? `https://buttondown.com/weekly-thing/archive/${number}/`,
    domains: extracted.domains,
    links: extracted.links,
    notable_links: extracted.notable_links,
    briefly_links: extracted.briefly_links,
    word_count: extracted.word_count,
    ...(opts.audio ?? {}),
  };
}

function yamlScalar(value: string): string {
  if (value === '') return "''";
  // Quote anything YAML would otherwise reinterpret as a number, date, or map.
  if (/^[\d\-+.]/.test(value) || /[:#]/.test(value)) {
    return `'${value.replace(/'/g, "''")}'`;
  }
  return value;
}

function yamlLinks(links: IssueLink[]): string[] {
  const out: string[] = ['links:'];
  for (const link of links) {
    out.push(`- text: ${yamlScalar(link.text)}`);
    out.push(`  url: ${link.url}`);
    out.push(`  domain: ${link.domain}`);
    out.push(`  heading_context: ${yamlScalar(link.heading_context)}`);
    out.push(`  section: ${link.section}`);
  }
  return out;
}

/** `apps/site/archive/{N}.md` — the generated issue page. */
export function archivePage(doc: IssueDoc, opts: SiteInputsOptions = {}): string {
  const e = issueEntry(doc, opts);
  const fm: string[] = ['---', 'layout: layouts/issue.njk'];

  fm.push(`buttondown_id: ${yamlScalar(e.id)}`);
  fm.push(`number: ${e.number}`);
  fm.push(`subject: ${yamlScalar(e.subject)}`);
  fm.push(`publish_date: '${e.publish_date}'`);
  fm.push(`slug: '${e.slug}'`);
  fm.push(`description: ${yamlScalar(e.description)}`);
  fm.push(`image: ${e.image}`);
  fm.push(`absolute_url: ${e.absolute_url}`);

  fm.push('domains:');
  for (const d of e.domains) fm.push(`- ${d}`);
  fm.push(...yamlLinks(e.links));

  fm.push(`word_count: ${e.word_count}`);
  fm.push(`permalink: /archive/${e.number}/`);
  fm.push('tags: issue');

  if (e.audio_url) {
    fm.push(`audio_url: ${e.audio_url}`);
    if (e.audio_duration_seconds !== undefined) {
      fm.push(`audio_duration_seconds: ${e.audio_duration_seconds}`);
    }
    if (e.audio_byte_size !== undefined) fm.push(`audio_byte_size: ${e.audio_byte_size}`);
    if (e.audio_voice) fm.push(`audio_voice: ${e.audio_voice}`);
  }

  fm.push('---');

  // The layout prints the title from front matter, so the body drops its H1.
  const body = renderWebsite(doc).replace(/^# .*\n\n?/, '');
  return `${fm.join('\n')}\n${GENERATED_NOTICE}\n${body}`;
}

// ── the archive feed ──────────────────────────────────────────────────────
//
// The corpus the Librarian API answers from. A separate leg that is not
// publishing (docs/decisions.md): it runs after the issue is out, is never a
// readiness gate, and receives text only. The commit lands in the archive
// repository's data/issues/{N}/, and that repository's CI rebuilds and
// uploads the corpus on any change under that path.
//
// The canonical shape mirrors the nine years of issues already there:
// front matter *without* the site page's layout, permalink, tags, or
// generator notice — those are materialized downstream when the archive
// builds its own pages — and without audio fields, because the archive
// receives no audio of any kind.

/** `data/issues/{N}/archive.md` — the canonical issue text. */
export function archiveMarkdown(doc: IssueDoc, opts: SiteInputsOptions = {}): string {
  const e = issueEntry(doc, opts);
  const fm: string[] = ['---'];

  // Field order matches the issues already in the store, so a diff of a
  // re-send reads as content, not as churn.
  fm.push(`buttondown_id: ${yamlScalar(e.id)}`);
  fm.push(`number: ${e.number}`);
  fm.push(`subject: ${yamlScalar(e.subject)}`);
  fm.push(`publish_date: '${e.publish_date}'`);
  fm.push(`slug: '${e.slug}'`);
  fm.push(`description: ${yamlScalar(e.description)}`);
  fm.push(`image: ${e.image}`);
  fm.push(`absolute_url: ${e.absolute_url}`);
  fm.push('domains:');
  for (const d of e.domains) fm.push(`- ${d}`);
  fm.push(...yamlLinks(e.links));
  fm.push(`word_count: ${e.word_count}`);
  fm.push('---');

  const body = renderWebsite(doc).replace(/^# .*\n\n?/, '');
  return `${fm.join('\n')}\n${body}`;
}

/** The three files the archive send commits, in the corpus's own shape. */
export function archiveInputs(doc: IssueDoc, opts: SiteInputsOptions = {}): RepoFile[] {
  const e = issueEntry(doc, opts);
  const dir = `data/issues/${e.number}`;

  const links = {
    notable_links: e.notable_links,
    briefly_links: e.briefly_links,
    domains: e.domains,
    word_count: e.word_count,
  };

  const metadata = {
    number: e.number,
    subject: e.subject,
    description: e.description,
    image: e.image,
    slug: e.slug,
    publish_date: e.publish_date,
    buttondown_id: e.id,
    absolute_url: e.absolute_url,
  };

  return [
    { path: `${dir}/archive.md`, content: archiveMarkdown(doc, opts) },
    { path: `${dir}/links.json`, content: `${JSON.stringify(links, null, 2)}\n` },
    { path: `${dir}/metadata.json`, content: `${JSON.stringify(metadata, null, 2)}\n` },
  ];
}

/**
 * The files the handoff commits. `emails.json` is rewritten whole from prior
 * entries plus this issue, so the index can never drift from the pages beside
 * it.
 *
 * `status.json` is deliberately NOT pushed. The site's /ops/ page reads it in
 * the retired Studio pipeline's shape (summary.total_issues, audio staleness
 * counts); overwriting it with a different shape would break the page while
 * looking like a successful handoff. It stays frozen until /ops/ is reworked
 * against WT Builder.
 */
export function siteInputs(doc: IssueDoc, opts: SiteInputsOptions = {}): RepoFile[] {
  const entry = issueEntry(doc, opts);
  const prior = (opts.priorEntries ?? []).filter((e) => e.number !== entry.number);
  const emails = [...prior, entry].sort((a, b) => a.number - b.number);

  return [
    { path: `apps/site/archive/${entry.number}.md`, content: archivePage(doc, opts) },
    { path: 'apps/site/_data/emails.json', content: `${JSON.stringify(emails, null, 2)}\n` },
  ];
}
