/**
 * Building the website edition's handoff.
 *
 * The render surface consumes generated 11ty inputs and knows nothing about
 * who produced them. Every field below was read off Studio's
 * `pipeline/content/content.py` and a real published archive page rather than
 * inferred, because the site's templates index into them: `links` drives the
 * per-issue link list, `domains` the fingerprint, `word_count` the stats, and
 * the `audio_*` fields the podcast enclosure.
 */

import type { IssueDoc, Item } from '../shared/types.ts';
import { renderWebsite } from '../shared/render/website.ts';
import { planEdition, bodyLines } from '../shared/render/plan.ts';
import { inertTemplate } from '../shared/render/email.ts';
import { CDN_HOST } from './integrations/images.ts';
import type { RepoFile } from './integrations/github.ts';

/**
 * Studio stamps its own generator here and its parser accepts three historical
 * variants. Ours names WT Builder, so a tool re-reading these files must be
 * taught this string too.
 */
export const GENERATED_NOTICE =
  '<!-- Generated by WT Builder from the canonical issue; do not edit directly. -->';

/**
 * The same notice on a back-catalogue page (WT1–WT349), which is re-rendered
 * from the archive's `data/issues/{N}/archive.md` rather than authored here.
 * It replaced Studio's line naming `pipeline/content/content.py`, which no
 * longer exists.
 */
export const RERENDER_NOTICE =
  '<!-- Generated by WT Builder (npm run rerender:archive) from data/issues; do not edit directly. -->';

export interface AudioChapter {
  start: number;
  title: string;
  url?: string;
  image?: string;
}

export interface AudioFields {
  audio_url?: string;
  audio_duration_seconds?: number;
  audio_byte_size?: number;
  audio_voice?: string;
  /** Podcasting 2.0 chapters and a WebVTT transcript, beside the mp3 on the CDN. */
  audio_chapters_url?: string;
  audio_transcript_url?: string;
  /**
   * The chapters inline, so the site can print show notes and a chapter list
   * — every link with the minute it is spoken at — without fetching.
   */
  audio_chapters?: AudioChapter[];
}

export interface IssueLink {
  text: string;
  url: string;
  domain: string;
  /** The Markdown link as it renders, which the site shows as context. */
  heading_context: string;
  section: string;
}

export interface IssueEntry extends AudioFields {
  id: string;
  number: number;
  subject: string;
  publish_date: string;
  slug: string;
  description: string;
  image: string;
  absolute_url: string;
  domains: string[];
  links: IssueLink[];
  notable_links: IssueLink[];
  briefly_links: IssueLink[];
  word_count: number;
}

/**
 * "WT349 — Owning the Rails", the form every published issue uses. A title
 * that is only the issue's own name carries no editorial content, so it
 * collapses to the bare "WT349" rather than printing "WT349 — 349".
 */
export function subjectFor(doc: IssueDoc): string {
  const n = doc.issue.number;
  const title = doc.issue.title
    .replace(/^The Weekly Thing\b/i, '')
    .replace(/^\s*(?:#|WT)?\s*/i, '')
    .trim();
  if (!title || title === String(n)) return `WT${n}`;
  return `WT${n} — ${title}`;
}

/**
 * The subject as Buttondown is handed it. Buttondown runs the subject through
 * the same template engine as the body, so a title carrying `{{` or `{%`
 * would run as code; the body's zero-width break applies here too (review
 * 2026-09-27 §3). The archive, the site and the podcast keep `subjectFor`.
 */
export function emailSubject(doc: IssueDoc): string {
  return inertTemplate(subjectFor(doc));
}

/** Noon UTC, matching every issue already in the archive. */
export function publishTimestamp(date: string): string {
  return `${date}T12:00:00Z`;
}

/** The generated cover art, at its conventional CDN path. */
export function coverImage(issueNumber: number): string {
  return `https://${CDN_HOST}/weekly-thing/${issueNumber}/cover.jpg`;
}

/** Jamie's own properties, which are never outbound links. */
function isOwnDomain(host: string): boolean {
  const bare = host.replace(/^www\./, '');
  return bare === 'thingelstad.com' || bare.endsWith('.thingelstad.com');
}

function hostOf(url: string): string | null {
  try {
    return new URL(url).hostname;
  } catch {
    return null;
  }
}

function linkFor(item: Item, section: string): IssueLink | null {
  const url = item.source_url;
  if (!url) return null;
  const domain = hostOf(url);
  if (!domain) return null;
  const text = item.title ?? url;
  // Raw, as the page called itself: heading_context feeds emails.json,
  // links.json, the site's issue-links feed and the Librarian, none of which
  // renders Markdown. Escaping belongs to the page body (website.ts).
  return { text, url, domain, heading_context: `[${text}](${url})`, section };
}

export interface ExtractedLinks {
  links: IssueLink[];
  notable_links: IssueLink[];
  briefly_links: IssueLink[];
  domains: string[];
  word_count: number;
}

/**
 * Links, their sections, the domain fingerprint, and the issue's word count —
 * all derived from the website edition, so they describe what actually shipped.
 */
export function extractLinks(doc: IssueDoc): ExtractedLinks {
  const links: IssueLink[] = [];
  const notable: IssueLink[] = [];
  const briefly: IssueLink[] = [];
  const domains = new Set<string>();
  let words = 0;

  for (const planned of planEdition(doc, 'website')) {
    const section = planned.node.label;
    for (const { item } of planned.items) {
      for (const text of [item.body, item.commentary, item.title]) {
        const flat = bodyLines(text).join(' ');
        if (flat) words += flat.split(/\s+/).filter(Boolean).length;
      }

      if (item.type === 'pinboard_link') {
        const link = linkFor(item, section);
        if (link) {
          links.push(link);
          if (section.toLowerCase() === 'notable') notable.push(link);
          if (section.toLowerCase() === 'briefly') briefly.push(link);
        }
      }

      // Every *outbound* host counts toward the fingerprint, including links
      // written inline in prose. Jamie's own blog is not outbound — a Journal
      // post linking to thingelstad.com is the issue citing itself, and no
      // published issue lists it.
      const urls = [item.source_url ?? ''];
      for (const m of String(item.body ?? '').matchAll(/\]\((https?:\/\/[^)\s]+)/g)) {
        urls.push(m[1]!);
      }
      for (const url of urls) {
        const host = url ? hostOf(url) : null;
        if (host && !isOwnDomain(host)) domains.add(host);
      }
    }
  }

  return {
    links,
    notable_links: notable,
    briefly_links: briefly,
    domains: [...domains].sort(),
    word_count: words,
  };
}

export interface SiteInputsOptions {
  /** Buttondown's id and archive URL, which exist only once the email is drafted. */
  buttondownId?: string;
  absoluteUrl?: string;
  audio?: AudioFields;
  /**
   * The site's emails.json as it stands, parsed. The handoff merges into
   * this — nine years of Shortcuts-era entries carry links, audio fields,
   * original slugs, and Buttondown ids the Builder's records cannot
   * reproduce, so the file is authoritative for every issue except the one
   * being sent. Rebuilding it from a projection gutted it once (2026-08-30,
   * 104k lines to 10k, reverted); this field being required is the scar.
   */
  currentEmails?: IssueEntry[];
}

export function issueEntry(doc: IssueDoc, opts: SiteInputsOptions = {}): IssueEntry {
  const number = doc.issue.number;
  const extracted = extractLinks(doc);
  return {
    id: opts.buttondownId ?? '',
    number,
    subject: subjectFor(doc),
    publish_date: publishTimestamp(doc.issue.publication_date),
    slug: String(number),
    description: doc.issue.dek ?? '',
    image: coverImage(number),
    absolute_url:
      opts.absoluteUrl ?? `https://buttondown.com/weekly-thing/archive/${number}/`,
    domains: extracted.domains,
    links: extracted.links,
    notable_links: extracted.notable_links,
    briefly_links: extracted.briefly_links,
    word_count: extracted.word_count,
    ...(opts.audio ?? {}),
  };
}

/**
 * Every string scalar in the front matter, written as a JSON string — which
 * is always a valid YAML double-quoted scalar. A title is whatever the
 * bookmarked page called itself: "[2410.12345] …", a leading quote, `@`,
 * `*`, `!`, `|`, `{`, or "&copy; and …" each broke the site build (or parsed
 * silently as something else) under the old quote-when-it-looks-risky rule,
 * and a failed build blocks every later deploy (review 2026-09-27 §1.3).
 * Uniform quoting was chosen over a "safe pattern" on 2026-09-28; the one-time
 * diff on re-sent pages was accepted. Numbers stay bare.
 */
export function yamlString(value: string): string {
  return JSON.stringify(value);
}

/**
 * The audio fields as front-matter lines — the website's record of an
 * episode. The back catalogue's renderer writes these same lines into the
 * archive pages it never generated, so the two cannot drift.
 */
export function audioFrontMatter(e: AudioFields): string[] {
  const fm: string[] = [];
  if (!e.audio_url) return fm;
  fm.push(`audio_url: ${yamlString(e.audio_url)}`);
  if (e.audio_duration_seconds !== undefined) {
    fm.push(`audio_duration_seconds: ${e.audio_duration_seconds}`);
  }
  if (e.audio_byte_size !== undefined) fm.push(`audio_byte_size: ${e.audio_byte_size}`);
  if (e.audio_voice) fm.push(`audio_voice: ${yamlString(e.audio_voice)}`);
  if (e.audio_chapters_url) fm.push(`audio_chapters_url: ${yamlString(e.audio_chapters_url)}`);
  if (e.audio_transcript_url) fm.push(`audio_transcript_url: ${yamlString(e.audio_transcript_url)}`);
  if (e.audio_chapters?.length) {
    fm.push('audio_chapters:');
    for (const c of e.audio_chapters) {
      fm.push(`- start: ${c.start}`);
      fm.push(`  title: ${yamlString(c.title)}`);
      if (c.url) fm.push(`  url: ${yamlString(c.url)}`);
      if (c.image) fm.push(`  image: ${yamlString(c.image)}`);
    }
  }
  return fm;
}

function yamlLinks(links: IssueLink[]): string[] {
  const out: string[] = ['links:'];
  for (const link of links) {
    out.push(`- text: ${yamlString(link.text)}`);
    out.push(`  url: ${yamlString(link.url)}`);
    out.push(`  domain: ${yamlString(link.domain)}`);
    out.push(`  heading_context: ${yamlString(link.heading_context)}`);
    out.push(`  section: ${yamlString(link.section)}`);
  }
  return out;
}

/** `apps/site/archive/{N}.md` — the generated issue page. */
export function archivePage(doc: IssueDoc, opts: SiteInputsOptions = {}): string {
  const e = issueEntry(doc, opts);
  const fm: string[] = ['---', `layout: ${yamlString('layouts/issue.njk')}`];

  fm.push(`buttondown_id: ${yamlString(e.id)}`);
  fm.push(`number: ${e.number}`);
  fm.push(`subject: ${yamlString(e.subject)}`);
  fm.push(`publish_date: ${yamlString(e.publish_date)}`);
  fm.push(`slug: ${yamlString(e.slug)}`);
  fm.push(`description: ${yamlString(e.description)}`);
  fm.push(`image: ${yamlString(e.image)}`);
  fm.push(`absolute_url: ${yamlString(e.absolute_url)}`);

  fm.push('domains:');
  for (const d of e.domains) fm.push(`- ${yamlString(d)}`);
  fm.push(...yamlLinks(e.links));

  fm.push(`word_count: ${e.word_count}`);
  fm.push(`permalink: ${yamlString(`/archive/${e.number}/`)}`);
  fm.push(`tags: ${yamlString('issue')}`);
  // The site preprocesses Markdown with Nunjucks (markdownTemplateEngine:
  // "njk"), and this page is words from the issue and from the sources: a
  // bookmark titled with {{ broke the whole site build, and {% if %} in a
  // comment printed nothing. A generated page needs no Nunjucks of its own;
  // the layout still renders as Nunjucks around it.
  fm.push(`templateEngineOverride: ${yamlString('md')}`);

  fm.push(...audioFrontMatter(e));

  fm.push('---');

  // The layout prints the title from front matter, so the body drops its H1.
  const body = renderWebsite(doc).replace(/^# .*\n\n?/, '');
  return `${fm.join('\n')}\n${GENERATED_NOTICE}\n${body}`;
}

// ── the archive feed ──────────────────────────────────────────────────────
//
// The corpus the Librarian API answers from. A separate leg that is not
// publishing (docs/decisions.md): it runs after the issue is out, is never a
// readiness gate, and receives text only. The commit lands in the archive
// repository's data/issues/{N}/, and that repository's CI rebuilds and
// uploads the corpus on any change under that path.
//
// The canonical shape mirrors the nine years of issues already there:
// front matter *without* the site page's layout, permalink, tags, or
// generator notice — those are materialized downstream when the archive
// builds its own pages — and without audio fields, because the archive
// receives no audio of any kind.

/** `data/issues/{N}/archive.md` — the canonical issue text. */
export function archiveMarkdown(doc: IssueDoc, opts: SiteInputsOptions = {}): string {
  const e = issueEntry(doc, opts);
  const fm: string[] = ['---'];

  // Field order matches the issues already in the store, so a diff of a
  // re-send reads as content, not as churn.
  fm.push(`buttondown_id: ${yamlString(e.id)}`);
  fm.push(`number: ${e.number}`);
  fm.push(`subject: ${yamlString(e.subject)}`);
  fm.push(`publish_date: ${yamlString(e.publish_date)}`);
  fm.push(`slug: ${yamlString(e.slug)}`);
  fm.push(`description: ${yamlString(e.description)}`);
  fm.push(`image: ${yamlString(e.image)}`);
  fm.push(`absolute_url: ${yamlString(e.absolute_url)}`);
  fm.push('domains:');
  for (const d of e.domains) fm.push(`- ${yamlString(d)}`);
  fm.push(...yamlLinks(e.links));
  fm.push(`word_count: ${e.word_count}`);
  fm.push('---');

  const body = renderWebsite(doc).replace(/^# .*\n\n?/, '');
  return `${fm.join('\n')}\n${body}`;
}

/** The three files the archive send commits, in the corpus's own shape. */
export function archiveInputs(doc: IssueDoc, opts: SiteInputsOptions = {}): RepoFile[] {
  const e = issueEntry(doc, opts);
  const dir = `data/issues/${e.number}`;

  const links = {
    notable_links: e.notable_links,
    briefly_links: e.briefly_links,
    domains: e.domains,
    word_count: e.word_count,
  };

  const metadata = {
    number: e.number,
    subject: e.subject,
    description: e.description,
    image: e.image,
    slug: e.slug,
    publish_date: e.publish_date,
    buttondown_id: e.id,
    absolute_url: e.absolute_url,
  };

  return [
    { path: `${dir}/archive.md`, content: archiveMarkdown(doc, opts) },
    { path: `${dir}/links.json`, content: `${JSON.stringify(links, null, 2)}\n` },
    { path: `${dir}/metadata.json`, content: `${JSON.stringify(metadata, null, 2)}\n` },
  ];
}

/**
 * The files the handoff commits. `emails.json` is merged: the site's current
 * entries preserved verbatim, plus this issue's own — so the index can never
 * drift from the pages beside it, and can never lose what the site knew.
 *
 * There is no status.json here. The old pipeline pushed one for the site's
 * /ops/ page; both are retired — this application's dashboard is the ops
 * surface, live on the tailnet where the operator actually is.
 */
export function siteInputs(doc: IssueDoc, opts: SiteInputsOptions = {}): RepoFile[] {
  const entry = issueEntry(doc, opts);
  if (!opts.currentEmails) {
    throw new Error(
      'siteInputs needs the site\u2019s current emails.json entries \u2014 refusing to rewrite the index from a projection',
    );
  }
  const preserved = opts.currentEmails.filter((e) => e.number !== entry.number);
  const emails = [...preserved, entry].sort((a, b) => a.number - b.number);

  return [
    { path: `apps/site/archive/${entry.number}.md`, content: archivePage(doc, opts) },
    { path: 'apps/site/_data/emails.json', content: `${JSON.stringify(emails, null, 2)}\n` },
  ];
}
